# Isomorfismo de grafos

Dos grafos $G=(V,E)$ y $G_0=(V_0,E_0)$ son isomorfos si y solo si existe
una matriz de permutación $P$ y algún orden de sus vértices, tal que sus
matrices de adyacencia $A(G)$ y $A(G_0)$ son iguales.

\begin{align}
A(G) = P \times A(G_0) \times P^T
\end{align}

In [51]:
import numpy as np

class abstract_graph:
    
    def __init__(self,_edges):
        self.edges=_edges
        self.nodes={u for u,v in self.edges} | {v for u,v in self.edges}
        
    def adjacency_matrix(self):
        pass
    
    def adjacency_list(self):
        pass
    
class simple_graph(abstract_graph):
    
    def __init__(self,_edges):
        tmp=[]
        for (u,v) in _edges:
            if (v,u) not in tmp and v!=u:
                tmp.append((u,v))
        self.edges=tmp
        self.nodes={u for u,v in _edges} | {v for u,v in _edges}
     
    def adjacency_matrix(self):
        # completar
        n=len(self.nodes)
        mat=np.zeros((n,n))
        for i,v in enumerate(self.nodes):
            for j,k in enumerate(self.nodes):
                if (v,k) in self.edges:
                    mat[i,j]=1
                    mat[j,i]=1
        return mat
    
    
    def adjacency_list(self):
        adjacent=lambda n : {v for u,v in self.edges if u==n } | {u for u,v in self.edges if v==n}
        return {v:adjacent(v) for v in self.nodes}
        
    

E=[('V1','V4'),('V1','V3'),('V3','V5'),('V2','V5'),('V2', 'V4')]
G=simple_graph(E)
print('aristas',G.edges)
print('nodos : ',G.nodes)
print('matriz adyacencia : ',G.adjacency_matrix())
print('lista adyacencia : ',G.adjacency_list())


aristas [('V1', 'V4'), ('V1', 'V3'), ('V3', 'V5'), ('V2', 'V5'), ('V2', 'V4')]
nodos :  {'V4', 'V3', 'V2', 'V1', 'V5'}
matriz adyacencia :  [[0. 0. 1. 1. 0.]
 [0. 0. 0. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 0. 0. 0.]
 [0. 1. 1. 0. 0.]]
lista adyacencia :  {'V4': {'V1', 'V2'}, 'V3': {'V1', 'V5'}, 'V2': {'V4', 'V5'}, 'V1': {'V4', 'V3'}, 'V5': {'V3', 'V2'}}


In [67]:
def permutation_matrix(perm):
    n=len(perm)
    P=np.zeros((n,n))
    for i in range(n):
        P[i,perm[i]]=1
    return P

In [68]:
n=len(G.nodes)
perm=np.random.permutation(range(n))
P=permutation_matrix(perm)

In [70]:
def get_edge_list(A):
    E=[]
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            if A[i,j]==1:
                E.append((i,j))
    return E

In [71]:
A2=P.dot(G.adjacency_matrix()).dot(P.T)
E2=get_edge_list(A2)

In [72]:
G2=simple_graph(E2)
print('aristas',G2.edges)
print('nodos : ',G2.nodes)
print('matriz adyacencia : ',G2.adjacency_matrix())
print('lista adyacencia : ',G2.adjacency_list())

aristas [(0, 2), (0, 4), (1, 3), (1, 4), (2, 3)]
nodos :  {0, 1, 2, 3, 4}
matriz adyacencia :  [[0. 0. 1. 0. 1.]
 [0. 0. 0. 1. 1.]
 [1. 0. 0. 1. 0.]
 [0. 1. 1. 0. 0.]
 [1. 1. 0. 0. 0.]]
lista adyacencia :  {0: {2, 4}, 1: {3, 4}, 2: {0, 3}, 3: {1, 2}, 4: {0, 1}}


In [77]:
def is_isomorphic_permutation(A1,A2,P):
    An=P.dot(A1).dot(P.T)
    return np.array_equal(A2,An)

In [78]:
is_isomorphic_permutation(G2.adjacency_matrix(),G.adjacency_matrix(),P.T)

True

In [83]:
import itertools as it

def is_isomorphic(A1,A2):
    n=A1.shape[0]
    for p in it.permutations(range(n)):
        P=permutation_matrix(perm)
        if is_isomorphic_permutation(A1,A2,P.T) or is_isomorphic_permutation(A1,A2,P):
            return True
    return False

In [84]:
is_isomorphic(G2.adjacency_matrix(),G.adjacency_matrix())

True

In [85]:
is_isomorphic(G.adjacency_matrix(),G2.adjacency_matrix())

True

# isomorfismo de ssub

In [105]:
P[0:1]

array([[0., 0., 0., 0., 1.]])

In [104]:
P[0:1].dot(G.adjacency_matrix()).dot(P[0:1].T)

array([[0.]])

In [103]:
G2.adjacency_matrix()[0:1,0:1]

array([[0.]])

In [96]:
P[0:2]

array([[0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.]])

In [97]:
P[0:2].dot(G.adjacency_matrix()).dot(P[0:2].T)

array([[0., 0.],
       [0., 0.]])

In [99]:
G2.adjacency_matrix()[0:2,0:2]

array([[0., 0.],
       [0., 0.]])

In [100]:
P[0:3]

array([[0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [101]:
P[0:3].dot(G.adjacency_matrix()).dot(P[0:3].T)

array([[0., 0., 1.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [102]:
G2.adjacency_matrix()[0:3,0:3]

array([[0., 0., 1.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [106]:
P[0:4]

array([[0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [107]:
P[0:4].dot(G.adjacency_matrix()).dot(P[0:4].T)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.]])

In [108]:
G2.adjacency_matrix()[0:4,0:4]

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.]])